# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.BatchSizeFinder.html#lightning.pytorch.callbacks.BatchSizeFinder

batch_size_finder:
  _target_: lightning.pytorch.callbacks.BatchSizeFinder
  mode: power
  steps_per_trial: 3
  init_val: 128
  max_trials: 25
  batch_arg_name: batch_size
