# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.LearningRateMonitor.html#lightning.pytorch.callbacks.DeviceStatsMonitor

lr_monitor:
  _target_: lightning.pytorch.callbacks.DeviceStatsMonitor
  cpu_stats: True
