# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.Timer.html#lightning.pytorch.callbacks.Timer

timer:
  _target_: lightning.pytorch.callbacks.Timer
  duration: "07:00:00:00" # 7 days
  interval: epoch
  verbose: True
