# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.Timer.html#lightning.pytorch.callbacks.Timer

timer:
  _target_: lightning.pytorch.callbacks.Timer
  duration: "02:00:00:00" # 2 days
  interval: epoch
  verbose: True
