# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.Timer.html#lightning.pytorch.callbacks.Timer

timer:
  _target_: lightning.pytorch.callbacks.Timer
  duration: "00:06:00:00" # 6 hours
  interval: epoch
  verbose: True
