# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.LearningRateMonitor.html#lightning.pytorch.callbacks.LearningRateMonitor

jump_cl_freezer:
  _target_: src.callbacks.freeze.JUMPCLFreezer

  unfreeze_image_encoder_at_epoch: ???
  image_backbone: [image_encoder, model]
  image_encoder_lr: null  # if null, uses the same as the first param group
  image_initial_denom_lr: null  # if image_encoder_lr is null, divides the first param group's lr by this

  unfreeze_molecule_encoder_at_epoch: ???
  molecule_backbone: [molecule_encoder, base_model]
  molecule_encoder_lr: null
  molecule_initial_denom_lr: null
