name: jump_models

channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - nodefaults

dependencies:
  - python=3.10.10
  - mamba
  - pip
  - conda-lock
  - poetry=1.5
  - llvmlite=0.40.1
  - pytorch::pytorch-cuda=11.8
  # - pytorch::pytorch=2.0.0
  # - pytorch::torchvision=0.15.0
  # - pytorch::torchaudio=2.0.0
  # - pyg::pyg=2.3.0
  # - lightning=2.0.4

platforms:
  - linux-64
  - win-64
