defaults:
  - /model/optimizer/adamw.yaml@model.optimizer
  - /model/scheduler/cosine_annealing_with_warmup.yaml@model.scheduler
  - /trainer/gpu.yaml@trainer
  - /callbacks/eval/hint.yaml@callbacks


model:
  _target_: src.eval.clinical_prediction.module.HintClinicalModule

  phase: ???  # "I", "II", "III"

  lr: 1e-4

  compound_transform: ${data.compound_transform}

  scheduler:
    warmup_epochs: 5
    max_epochs: ${eval.default_hint.trainer.max_epochs}

  example_input_path: ${model.example_input_path}

  split_lr_in_groups: False


datamodule:
  _target_: src.eval.clinical_prediction.datamodule.HintClinicalDataModule

  phase: ???  # "I", "II", "III"

  hint_dir: ${paths.data_root_dir}/hint-clinical-trial-outcome-prediction/data

  smiless_col: smiless
  label_col: label
  batch_size: 256
  num_workers: 16
  pin_memory: False
  prefetch_factor: 2
  drop_last: False


trainer:
  default_root_dir: ${paths.output_dir}/eval/hint/default_hint
  devices: ${trainer.devices}
  min_epochs: 0
  max_epochs: 50
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  check_val_every_n_epoch: 1


evaluator:
  _target_: src.eval.evaluators.Evaluator
  name: ???
  visualize_kwargs: null


callbacks:
  early_stopping:
    monitor: ???

  model_checkpoint:
    monitor: ??? # hint/phase_I/val/loss
    dirpath: ??? # ${eval.default_hint.trainer.default_root_dir}/checkpoints

  wandb_plotter:
    prefix: ??? # hint/phase_II

