defaults:
  - /model/optimizer/adam.yaml@phase_II.model.optimizer
  - /model/scheduler/on_plateau_with_warmup.yaml@phase_II.model.scheduler
  - /trainer/gpu.yaml@phase_II.trainer
  - /callbacks/eval/hint.yaml@phase_II.callbacks

phase_II:
  model:
    _target_: src.eval.clinical_prediction.module.HintClinicalModulePhaseII

    lr: 1e-3

    compound_transform: ${data.compound_transform}

    scheduler:
      warmup_steps: [10]

    example_input_path: ${model.example_input_path}
    # example_input_path: ${paths.data_root_dir}/jump/models/eval/test/example.pt


  datamodule:
    _target_: src.eval.clinical_prediction.datamodule.HintClinicalDataModulePhaseII

    hint_dir: ${paths.data_root_dir}/hint/

    smiless_col: smiless
    label_col: label
    batch_size: 256
    num_workers: 16
    pin_memory: False
    prefetch_factor: 3
    drop_last: False


  trainer:
    default_root_dir: ${paths.output_dir}/eval/hint/phase_II/
    devices: ${trainer.devices}
    min_epochs: 0
    max_epochs: 200
    log_every_n_steps: 1
    # gradient_clip_val: 0.5
    num_sanity_val_steps: 1
    check_val_every_n_epoch: 1


  evaluator:
    _target_: src.eval.evaluators.Evaluator
    visualize_kwargs: null


  callbacks:
    early_stopping:
      monitor: hint/phase_I/val/loss

    model_checkpoint:
      monitor: hint/phase_I/val/loss
      dirpath: ${eval.phase_II.trainer.default_root_dir}/checkpoints

