defaults:
  - /trainer/gpu.yaml@idr_graph_retrieval.trainer

idr_graph_retrieval:
  model:
    _target_: src.eval.retrieval.module.IDRRetrievalModule
    example_input_path: null


  datamodule:
    _target_: src.eval.retrieval.datamodule.IDRRetrievalDataModule


    image_metadata_path: ${paths.data_root_dir}/idr0033-rohban-pathways/processed_metadata.csv
    excape_db_path: ${paths.data_root_dir}/excape-db/excape_db_df.csv
    selected_group_path: ${paths.data_root_dir}/excape-db/processed_groups.json

    data_root_dir: ${paths.data_root_dir}/screen_1751
    image_batch_size: 128
    compound_batch_size: 1
    num_workers: 16
    pin_memory: false
    prefetch_factor: 2

    compound_transform: ${data.compound_transform}

    transform: ${data.transform}

    image_gene_col: "Gene Symbol"
    col_fstring: "FileName_{channel}"
    channels: null
    target_col: "Activity_Flag"
    smiles_col: "SMILES"



  trainer:
    default_root_dir: ${paths.output_dir}/eval/retrieval/idr/
    devices: ${trainer.devices}


  evaluator:
    _target_: src.eval.retrieval.evaluator.IDRRetrievalEvaluator
    name: IDRRetrieval
    visualize_kwargs: null


  callbacks: null
