defaults:
  - override /data/compound_transform@_global_.data.compound_transform: fp_transform.yaml

_target_: src.modules.molecules.fp_mlp.FingerprintsWithMLP
input_dim: 2167  # This depends on the number of features in the concatenated fingerprint
out_dim: 128
embedding_dim: [512,256]
activation_layer:
  _target_: torch.nn.ReLU
  _partial_: true
norm_layer:
  _target_: torch.nn.LayerNorm
  _partial_: true
dropout: 0.1
