# https://lifesci.dgl.ai/api/model.pretrain.html

_target_: src.modules.molecules.dgllife_gat.GATPretrainedWithLinearHead
pretrained_name: "GAT_canonical_PCBA"
out_dim: ${model.embedding_dim}
pooling: mean
preload: True
