# https://lifesci.dgl.ai/api/model.pretrain.html

defaults:
  - override /data/compound_transform@_global_.data.compound_transform: dgllife_gin.yaml
  - override /data/collate_fn@_global_.data.collate_fn: image_graph.yaml

_target_: src.modules.molecules.dgllife_gin.GINPretrainedWithLinearHead
pretrained_name: "gin_supervised_masking"
out_dim: ${model.embedding_dim}
pooling: mean
preload: True
