defaults:
  - /eval/batch_effect/default.yaml@batch_normalized

batch_normalized:

  evaluator:
    _target_: src.eval.batch_effect.evaluator.BatchEffectEvaluator

    dmso_normalize: batch
    normalize_cls:
      _target_: src.eval.batch_effect.spherize.ZCA_corr
      _partial_: true
