defaults:
  - /eval/batch_effect/default.yaml@batch_normalized_standard

batch_normalized_standard:

  evaluator:
    _target_: src.eval.batch_effect.evaluator.BatchEffectEvaluator

    dmso_normalize: batch
    normalize_cls:
      _target_: sklearn.preprocessing.StandardScaler
      _partial_: true
