defaults:
  - /model/optimizer/adamw.yaml@batch_effect_random.model.optimizer
  - /model/scheduler/cosine_annealing_with_warmup.yaml@batch_effect_random.model.scheduler
  - /trainer/gpu.yaml@batch_effect_random.trainer
  - /callbacks/eval/batch_effect.yaml@batch_effect_random.callbacks  #! This adds the callbacks

batch_effect_random:
  model:
    _target_: src.eval.batch_effect.module.BatchEffectModule

    split_name: random
    lr: 1e-4
    num_classes: 118

    scheduler:
      warmup_epochs: 3
      max_epochs: ${eval.batch_effect_random.trainer.max_epochs}

    example_input_path: ${model.example_input_path}

    split_lr_in_groups: False


  datamodule:
    _target_: src.eval.batch_effect.datamodule.BatchEffectDataModule

    split_type: random

    split_path: ${paths.data_root_dir}/jump/models/eval/batch_effect/splits/default/
    target_load_df_path:  ${paths.data_root_dir}/jump/models/eval/batch_effect/splits/target_load_df.csv

    val_size: 0.1
    test_size: 0.2

    batch_size: 128
    num_workers: 16
    pin_memory: False
    prefetch_factor: 2
    drop_last: False

    transform: ${data.transform}

    metadata_path: ${paths.raw_metadata_path}
    load_data_path: ${paths.load_data_path}
    data_root_dir: null
    label_col: target

    random_state: 42

    # collate_fn: null
    # example_input_path: ${paths.data_root_dir}/jump/models/eval/test/example.pt


  trainer:
    default_root_dir: ${paths.output_dir}/eval/batch_effect/random
    devices: ${trainer.devices}
    min_epochs: 0
    max_epochs: 25
    log_every_n_steps: 1
    # gradient_clip_val: 0.5
    num_sanity_val_steps: 1
    check_val_every_n_epoch: 1


  evaluator:
    _target_: src.eval.evaluators.Evaluator
    name: BatchEffectRandom
    visualize_kwargs: null


  callbacks:
    early_stopping:
      monitor: batch_effect/random/val/loss

    model_checkpoint:
      monitor: batch_effect/random/val/loss
      dirpath: ${eval.batch_effect_random.trainer.default_root_dir}/checkpoints

    wandb_plotter:
      prefix: batch_effect/random

