defaults:
  - /eval/batch_effect/default.yaml@source_normalized_standard

source_normalized_standard:

  evaluator:
    _target_: src.eval.batch_effect.evaluator.BatchEffectEvaluator

    dmso_normalize: source
    normalize_cls:
      _target_: sklearn.preprocessing.StandardScaler
      _partial_: true
