defaults:
  - /model/optimizer/adam.yaml@moa_image_task.model.optimizer
  - /model/scheduler/exponential.yaml@moa_image_task.model.scheduler
  - /trainer/gpu.yaml@moa_image_task.trainer
  - /callbacks/eval/moa.yaml@moa_image_task.callbacks  #! This adds the callbacks

moa_image_task:
  evaluator:
    _target_: src.eval.evaluators.Evaluator
    name: JumpMOAImageModule
    visualize_kwargs: null


  callbacks:
    model_checkpoint:
      dirpath: ${eval.moa_image_task.trainer.default_root_dir}/checkpoints

    image_freezer:
      unfreeze_backbone_at_epoch: 11
      backbone_initial_ratio_lr: 5e-2
      group_name: moa_image_encoder_unfrozen



  datamodule:
    _target_: src.eval.moa.datamodule.JumpMOADataModule

    moa_load_df_path: ${paths.data_root_dir}/jump/models/eval/moa/image_task/moa_500_1024.csv
    split_path: ${paths.data_root_dir}/jump/models/eval/moa/image_task/splits/moa_500_1024/

    batch_size: 256
    num_workers: 16
    pin_memory: False
    prefetch_factor: 2

    transform: ${data.transform}

    metadata_dir: ${paths.raw_metadata_path}
    load_data_dir: ${paths.load_data_path}
    data_root_dir: null

    splitter:
      _target_: src.splitters.StratifiedSplitter
      train: 0.75
      val: 0.15
      test: 0.1

    max_obs_per_class: 1024
    min_obs_per_class: 500

    target_col: moa
    return_image: True
    smiles_col: smiles
    return_compound: False

    compound_transform: null
    collate_fn: null

    use_cache: True
    force_split: False


  model:
    _target_: src.eval.moa.module.JumpMOAImageModule

    lr: 1e-2
    num_classes: 9  # when min is set to 500, else 26

    scheduler:
      gamma: 0.92

    example_input_path: ${paths.data_root_dir}/jump/models/eval/test/example.pt


  trainer:
    default_root_dir: ${paths.output_dir}/eval/moa
    devices: ${trainer.devices}
    min_epochs: 0
    max_epochs: 100
    log_every_n_steps: 1
    gradient_clip_val: 0.5
    num_sanity_val_steps: 1
