_target_: src.models.jump_module.BasicJUMPModule

defaults:
  - image_encoder: resnet50
  - molecule_encoder: gin_supervised_infomax
  - criterion: contrastive
  - optimizer: adam
  - scheduler: exponential
  - _self_

embedding_dim: 1024

optimizer:
  lr: 5e-3

scheduler:
  gamma: 0.97

example_input_path: /projects/cpjump1/jump/models/example_batch/simple_jump_cl/batch.pth
