_target_: src.models.jump_module.BasicJUMPModule

defaults:
  - image_encoder: resnet50
  - molecule_encoder: gin_supervised_infomax
  - criterion: contrastive
  - optimizer: adam
  - scheduler: exponential
  - _self_

optimizer:
  lr: 1e-3

scheduler:
  gamma: 0.9
