_target_: src.models.jump_cl.module.BasicJUMPModule

defaults:
  - image_encoder: resnet18
  - molecule_encoder: fp_encoder
  - criterion: contrastive.yaml
  - optimizer: adam.yaml
  - scheduler: exponential.yaml
  - override /data/compound_transform@_global_.data.compound_transform: fp_transform.yaml
  - _self_

embedding_dim: ???
lr: ???
batch_size: ${data.batch_size}

optimizer:
  lr: ${model.lr}

# /projects/cpjump1/jump/models/example_batch/simple_jump_cl/batch.pth
example_input_path: null

# args for the lr scheduler in pytorch lightning
monitor: val/loss  # metric to monitor for some schedulers
interval: epoch    # epoch or step
frequency: 1       # how often to call the scheduler

image_backbone: backbone
image_head: projection_head
molecule_backbone: null
molecule_head: null
