_target_: src.models.jump_cl.module.BasicJUMPModule

defaults:
  - image_encoder: ???
  - molecule_encoder: ???
  - criterion: frozen_contrastive.yaml
  - optimizer: adam.yaml
  - scheduler: exponential.yaml
  - _self_

embedding_dim: ???
lr: ???
batch_size: ${data.batch_size}

optimizer:
  lr: ${model.lr}

# /projects/cpjump1/jump/models/example_batch/simple_jump_cl/batch.pth
example_input_path: ???

# args for the lr scheduler in pytorch lightning
monitor: val/loss  # metric to monitor for some schedulers
interval: epoch    # epoch or step
frequency: 1       # how often to call the scheduler

params_group_to_ignore: []
image_backbone: backbone
image_head: projection_head
molecule_backbone: backbone
molecule_head: projection_head
