_target_: src.models.jump_module.BasicJUMPModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3

scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  _partial_: true
  epochs: ${trainer.max_epochs}
  steps_per_epoch: 7
  max_lr: 5e-3

# scheduler:
  # _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
  # _partial_: true
  # warmup_epochs: 15
  # max_epochs: ${trainer.max_epochs}
  # warmup_start_lr: 1e-5
  # eta_min: 1e-7

image_encoder:
  _target_: src.images.image_encoder.CNNEncoder
  instance_model_name: resnet50
  target_num: 512
  n_channels: 5
  pretrained: True

molecule_encoder:
  _target_: src.models.simple_jump_cl.molecule_encoder.GINPretrainedWithLinearHead
  pretrained_name: "gin_supervised_infomax"
  out_dim: 512
  pretrained_dim: 300
  preload: True

criterion:
  _target_: src.losses.contrastive_loss_with_temperature.ContrastiveLossWithTemperature
