_target_: src.models.jump_cl.module.BasicJUMPModule

defaults:
  - image_encoder: ???
  - molecule_encoder: ???
  - criterion: contrastive.yaml
  - optimizer: adam.yaml
  - scheduler: exponential.yaml
  - _self_

embedding_dim: ???

optimizer:
  lr: ???

scheduler:
  gamma: 0.9

# /projects/cpjump1/jump/models/example_batch/simple_jump_cl/batch.pth
example_input_path: ???
