# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: ${oc.env:PROJECT_ROOT}

# metadata path
projects_dir: /projects
data_root_dir: ${paths.projects_dir}/cpjump1


metadata_path: ${paths.data_root_dir}/jump/models/metadata
raw_metadata_path: ${paths.data_root_dir}/jump/metadata
load_data_path: ${paths.data_root_dir}/jump/load_data
model_dir: ${paths.data_root_dir}/jump/s3_cache

# path to split folders
split_path: ${paths.data_root_dir}/jump/models/splits

# path to logging directory
log_dir: ${paths.data_root_dir}/jump/logs

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}
