defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - lr_monitor.yaml
  - batch_size_finder.yaml
  - lr_finder.yaml
  - jump_cl_freezer.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/loss"
  patience: 20
  mode: "min"

model_summary:
  max_depth: 2

jump_cl_freezer:
  unfreeze_image_encoder_at_epoch: 5
  image_encoder_lr: 0.0001
  unfreeze_molecule_encoder_at_epoch: 3
  molecule_encoder_lr: 0.001
