defaults:
  - lightning/model_checkpoint@_here_
  - lightning/early_stopping@_here_
  - lightning/model_summary@_here_
  - lightning/rich_progress_bar@_here_
  - lightning/lr_monitor@_here_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/loss"
  patience: 100
  mode: "min"

model_summary:
  max_depth: -1
