defaults:
  - /callbacks/lightning/rich_progress_bar@_here_
  - /callbacks/lightning/model_checkpoint@_here_
  - /callbacks/lightning/early_stopping@_here_
  # - /callbacks/lightning/lr_finder@_here_
  - /callbacks/custom/wandb_plotter@_here_
  - /callbacks/custom/nan_loss@_here_
  # - /callbacks/custom/molecule_freezer@_here_
  - /callbacks/lightning/lr_monitor@_here_


model_checkpoint:
  dirpath: ???
  filename: null
  monitor: ???
  mode: min
  save_last: False
  auto_insert_metric_name: null

early_stopping:
  monitor: ???
  patience: 25
  min_delta: 0
  mode: min

wandb_plotter:
  watch: False
  log_freq: 50
  plot_every_n_epoch: 1
  prefix: ???
  cmap: Oranges_r
  fmt: ".2f"
  per_fmt: ".1%"
  fz: 10
  lw: 0.5
  cbar: False
  figsize: [16,16]
