defaults:
  - /callbacks/lightning/rich_progress_bar@_here_
  - /callbacks/lightning/model_checkpoint@_here_
  - /callbacks/lightning/early_stopping@_here_
  - /callbacks/custom/wandb_plotter@_here_
  - /callbacks/custom/image_freezer@_here_
  - /callbacks/lightning/lr_monitor@_here_

model_checkpoint:
  dirpath: ???
  filename: "moa_epoch_{epoch:03d}"
  monitor: jump_moa/image/val/loss
  mode: min
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: jump_moa/image/val/loss
  patience: 10
  min_delta: 0
  mode: min

wandb_plotter:
  watch: False
  log_freq: 50
  plot_every_n_epoch: 5
  prefix: jump_moa/image/plots
  cmap: Oranges_r
  fmt: ".2f"
  per_fmt: ".1%"
  fz: 10
  lw: 0.5
  cbar: False
  figsize: [16,16]
