defaults:
  - /callbacks/lightning/rich_progress_bar@_here_
  - /callbacks/lightning/model_checkpoint@_here_
  - /callbacks/lightning/early_stopping@_here_
  - /callbacks/custom/wandb_watcher@_here_
  - /callbacks/custom/molecule_freezer@_here_
  - /callbacks/lightning/lr_monitor@_here_


model_checkpoint:
  dirpath: ???
  filename: "moa_epoch_{epoch:03d}"
  monitor: ???
  mode: min
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: ???
  patience: 10
  min_delta: 0
  mode: min

wandb_watcher:
  log_freq: 50
