defaults:
  - /callbacks/lightning/rich_progress_bar@_here_
  - /callbacks/lightning/model_checkpoint@_here_
  - /callbacks/lightning/lr_finder@_here_
  - /callbacks/lightning/early_stopping@_here_
  - /callbacks/custom/nan_loss@_here_
  # - /callbacks/custom/molecule_freezer@_here_
  - /callbacks/lightning/lr_monitor@_here_


model_checkpoint:
  dirpath: ???
  filename: null
  monitor: ???
  mode: min
  save_last: False
  auto_insert_metric_name: null

early_stopping:
  monitor: ???
  patience: 25
  min_delta: 0
  mode: min
