# @package _global_

defaults:
  - _self_
  - data: jump_cl.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: jump_cl.yaml
  - logger: wandb
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
