# @package _global_

defaults:
  - _self_
  - data: jump_cl.yaml
  - model: jump_cl.yaml
  - logger: wandb # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - eval: evaluators.yaml


task_name: "eval"

evaluate: True

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
