defaults:
  - /model/optimizer/adam.yaml@esol.model.optimizer
  - /model/scheduler/on_plateau_with_warmup.yaml@esol.model.scheduler
  - /trainer/gpu.yaml@esol.trainer
  - /callbacks/eval/ogb.yaml@esol.callbacks

esol:
  evaluator:
    _target_: src.eval.evaluators.Evaluator
    name: EsolModule
    visualize_kwargs: null


  callbacks:
    molecule_freezer:
      unfreeze_backbone_at_epoch: 11
      group_name: esol_molecule_unfrozen

    early_stopping:
      monitor: ogb/esol/image/val/loss

    model_checkpoint:
      monitor: ogb/esol/image/val/loss
      dirpath: ${eval.esol.trainer.default_root_dir}/checkpoints


  model:
    _target_: src.eval.ogb.module.EsolModule

    lr: 5e-3

    scheduler:
      warmup_steps: [10]

    example_input_path: ${paths.data_root_dir}/jump/models/eval/test/example.pt


  datamodule:
    _target_: src.eval.ogb.datamodule.EsolDataModule

    root_dir: ${paths.data_root_dir}/ogb/

    batch_size: 256
    num_workers: 16
    pin_memory: False
    prefetch_factor: 2

    compound_transform: ${data.compound_transform}

    split_type: scaffold

    smiles_col: smiles
    targets: null
    # collate_fn: null

    use_cache: False


  trainer:
    default_root_dir: ${paths.output_dir}/eval/ogb/esol/
    devices: ${trainer.devices}
    min_epochs: 0
    max_epochs: 100
    log_every_n_steps: 1
    gradient_clip_val: 0.5
    num_sanity_val_steps: 1
