_target_: src.modules.losses.contrastive_loss_with_temperature.ContrastiveLossWithTemperature
logit_scale: 2.718281828459045
logit_scale_min: 1e-3
logit_scale_max: 4.605170185988092
requires_grad: True
