_target_: src.modules.losses.contrastive_losses.InfoNCE
norm: True
temperature: 1
temperature_requires_grad: True  # If True, temperature is learned

temperature_min: 0      # Not used if requires_grad is False
temperature_max: 100
