_target_: src.modules.losses.contrastive_losses.InfoNCE
norm: True
temperature: 1
return_rank: True

temperature_requires_grad: False  # If True, temperature is learned

temperature_min: 0      # Not used if requires_grad is False
temperature_max: 100
