_target_: src.modules.losses.multiview_losses.MultiviewIntraModalNTXentLoss
norm: True
temperature: 0.5
return_rank: True
lambda_image: 0.5

temperature_requires_grad: False  # If True, temperature is learned

temperature_min: 0      # Not used if requires_grad is False
temperature_max: 100
