_target_: src.modules.losses.multiview_losses.NTXentLikelihoodLoss
emb_dim: ${model.embedding_dim}
norm: True
temperature: 0.5
return_rank: True

temperature_requires_grad: False  # If True, temperature is learned

temperature_min: 0      # Not used if requires_grad is False
temperature_max: 100
