# https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.CosineAnnealingLR.html#torch.optim.lr_scheduler.CosineAnnealingLR

_target_: torch.optim.lr_scheduler.CosineAnnealingLR
_partial_: true
T_max: ???
eta_min: 0
last_epoch: -1
