_target_: src.modules.lr_schedulers.warmup_wrapper.WarmUpWrapper
_partial_: True
warmup_steps:
  - ???
interpolation: linear

wrapped_scheduler: CosineAnnealingLR
T_max: ${trainer.max_epochs}
eta_min: 0
last_epoch: -1
