# https://huggingface.co/timm

_target_: src.modules.images.timm_pretrained.CNNEncoder
instance_model_name: vit_base_r50_s16_384.orig_in21k_ft_in1k
target_num: ${model.embedding_dim}
n_channels: 5
pretrained: True
